### ISSUE TITLE
Cannot connect to calls / meetings since June 30th OSX arm builds

### ISSUE THREAD

**Issue by mattabrams** [ItzLevvie/MicrosoftTeams-msinternal#12]
Unable to connect to calls / meetings since June 30th OSX ARM builds...resolved by reverting back to June 29th build...

**Comment by thbckup** [comment]
Seeing the same, Reverted back to 1.5.00.17909-E which doesn't have the issue.

**Comment by pleo624** [comment]
Same thing here. How do you revert back to the June 29th build?

**Comment by thbckup** [comment]
https://statics.teams.cdn.office.net/production-osx/1.5.00.17909/Teams_osx.pkg

**Comment by thbckup** [comment]
With the release of and upgrade to the Continuous Development version, the Issue was entirely resolved.

**Comment by hemersonmf** [comment]
> With the release of and upgrade to the Continuous Deployment version, the Issue was entirely resolved for M1 Pro MacBook Pro..

You are talking about the 1.5.00.18926 (osx-x64 + osx-arm64) version?

**Comment by thbckup** [comment]
Video still working with the new Version 1.5.00.19658.

Have had some random App-crash/App-Restart issues through the past week, prior to this release;
When other people start screen shares.
When a second device (iPad) joins the same call.
Changing Audio devices. Between Internal Mic+Speakers and Custom Setup (Yeti X + USB DAC)

It's Sunday night here, if the issues remain tomorrow I'll post again.

**Comment by hemersonmf** [comment]
Same problem with the version 1.5.00.19502:

_Have had some random App-crash/App-Restart issues through the past week, prior to this release;
When other people start screen shares.
When a second device (iPad) joins the same call._

_Changing Audio devices. Between Internal Mic+Speakers and Custom Setup (Yeti X + USB DAC)_
I'm using AirPods Pro, and sometimes I lost the connection with Teams (not Mac).

Now I will try 1.5.00.19709.

**Comment by blesio** [comment]
This has been fixed in the latest builds, as of last week I think.

**Comment by nutterthanos** [comment]
This is not where you post issues for Microsoft Teams

Please follow this
https://support.microsoft.com/en-us/office/how-do-you-report-an-issue-or-bug-a318252f-cc24-4e95-bec9-71bd2dbc379d#:~:text=To%20help%20us%20investigate%20the,Help%20%26%20Feedback%20%3E%20Contact%20Support.

**Comment by nutterthanos** [comment]
> > This is not where you post issues for Microsoft Teams
> > Please follow this https://support.microsoft.com/en-us/office/how-do-you-report-an-issue-or-bug-a318252f-cc24-4e95-bec9-71bd2dbc379d#:~:text=To%20help%20us%20investigate%20the,Help%20%26%20Feedback%20%3E%20Contact%20Support.
> > Im not an official Microsoft Employee btw just mentioning this since this is not Offical Microsoft Support here.
> 
> The issues and comments posted above were specific to the ARM Builds for Mac which are not yet fully supported by Microsoft support, intended only as guidance for the developers, and in turn the other users who are trying the latest releases to get back to a stable version.
> 
> The users currently on these Continuous Development and Exploration builds are not necessarily looking for a fully working product, We are looking to test the latest features and provide feedback to the Devs working hard on their projects.
> 
> To answer your unasked question, the link you provided is not applicable to us, but thank you for your input.

👍

**Comment by ItzLevvie** [comment]
You will need to file an issue over at https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
