### ISSUE TITLE
Host sharing Desktop can't click own mouse when other person is controlling

### ISSUE THREAD

**Issue by blesio** [ItzLevvie/MicrosoftTeams-msinternal#16]
When you share a desktop and give someone control of your desktop, you loose the ability to click your mouse, it works very sporadically, meaning you need to click 20 times before it actually clicks on something.  You even can't take away the control rights, starts working fine when the other person releases control of your desktop.
This happens on all MS Teams builds, still not fixed.

**Comment by nutterthanos** [comment]
This is not where you post issues for Microsoft Teams

Please follow this
https://support.microsoft.com/en-us/office/how-do-you-report-an-issue-or-bug-a318252f-cc24-4e95-bec9-71bd2dbc379d#:~:text=To%20help%20us%20investigate%20the,Help%20%26%20Feedback%20%3E%20Contact%20Support.

@ItzLevvie
