### ISSUE TITLE
Latest production builds are out of date in defconfig

### ISSUE THREAD

**Issue by earthsound** [ItzLevvie/MicrosoftTeams-msinternal#2]
E.g.: 

https://teams.microsoft.com/desktopclient/installer/windows/x64?ring=general returns https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.8872/Teams_windows_x64.exe

However, defconfig lists:
`1.4.00.7174 (win-x64) - published to CDN on Friday, March 12, 2021 at 3:39 PM with 104 MB: https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.7174/Teams_windows_x64.exe`

**Comment by ItzLevvie** [comment]
Hi - it may show old builds because currently the `defconfig` file is manually updated each day depending on what time I update it.

There was a CI system for this, but I've scrapped that for now, and will come back in the future.
