### ISSUE TITLE
MacOS-Arm64 - Videos Not Showing - Must Pin Videos to see them 

### ISSUE THREAD

**Issue by jfranconi** [ItzLevvie/MicrosoftTeams-msinternal#23]
Dropping this here as it was noted here by multiple users:

https://techcommunity.microsoft.com/t5/microsoft-teams-blog/announcing-microsoft-teams-optimized-for-apple-silicon/bc-p/3604649#M10970

* When running latest arm 64 builds the video preview does not show
* Have to “pin” video (host and attendees) to be able to see their video feeds
* Can consider video functionality broken
* Reproduced on Apple MacBook Pro M1
* Reported on M2 systems in thread above

**Comment by ItzLevvie** [comment]
You will need to file an issue over at https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
