### ISSUE TITLE
Broken OSX Ms teams update

### ISSUE THREAD

**Issue by hawwky** [ItzLevvie/MicrosoftTeams-msinternal#3]
guys you broke my ms teams running on m1 mba through rosetta 2 

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/79000630/141892309-c8e7892f-fff4-47d0-aa58-98ce636b20ea.png">

no menu to unmute and other stuff???

**Comment by hawwky** [comment]
latest build 1.4.00.29477

**Comment by hawwky** [comment]
uninstall, downgrade and upgrading worked for me. but please fix the bug

**Comment by ItzLevvie** [comment]
You will need to file an issue over at https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
