### ISSUE TITLE
Webhooks not displaying new lines correctly in Windows clients

### ISSUE THREAD

**Issue by deboer-rm** [ItzLevvie/MicrosoftTeams-msinternal#30]
Looks like it has something to do with how the windows client is interperetting "/n" or '<br>' 

More details and confirmation: https://answers.microsoft.com/en-us/msteams/forum/all/incoming-webhook-messages-not-displaying-in-latest/f42a0466-8a63-4523-a4c2-ee3d8463a0e3

**Comment by ItzLevvie** [comment]
You will need to file an issue over at https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
