### ISSUE TITLE
How to use the new macos webview2 pre version of teams app?

### ISSUE THREAD

**Issue by jgoldhammer** [ItzLevvie/MicrosoftTeams-msinternal#34]
I have downloaded the new webview2 based teams app for macos here:
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/3872101/221825452-9f3b7f81-d7cc-4941-a400-25076b3a2783.png">

Unfortunately I cannot test it by now as following message pops up:

<img width="2041" alt="image" src="https://user-images.githubusercontent.com/3872101/221825284-8fdc7a42-bcc9-44aa-a2aa-f11f7be8c48b.png">

What can I do to be able to test it?

Thanks

**Comment by LorenzoS92** [comment]
Any news?

**Comment by ItzLevvie** [comment]
You will need to wait until our Microsoft Teams engineering team releases Teams 2.1 to the Public Preview Channel.

**Comment by jgoldhammer** [comment]
Teams works now.
