### ISSUE TITLE
How to read the 2.0 and 2.1 version number

### ISSUE THREAD

**Issue by X-15** [ItzLevvie/MicrosoftTeams-msinternal#37]
Hi!
I tried to figure it out, but couldn't really. I can't find a pattern on my own, so I am asking:
For example this 2.1 version: 23095.300.1995.3049 <- how does one read that?

**Comment by ItzLevvie** [comment]
We use the `YYDDD.XXXX.XXXX.XXXX` format for build numbers.

We can use this as an example:
https://github.com/ItzLevvie/MicrosoftTeams-msinternal/blob/b04312a22b3b42c836e1345e3cf5954a59576387/defconfig2#L18

24 (YY) is the year.
011 (DDD) is the date.
400 is automatically generated by our CI system.
2624 is the amount of builds we created in total.
3087 is automatically generated by our CI system.
