### ISSUE TITLE
Teams Add-In for outlook not working with latest installation

### ISSUE THREAD

**Issue by rmillman** [ItzLevvie/MicrosoftTeams-msinternal#38]
With the installation of version: 23104.900.2020.2949
I no longer have the Teams add-in working  in my Outlook installation.
The add-in shows in my installed add-ins, but all traces of functionality are gone from outlook[desktop]. I haven't checked with web.

**Comment by ItzLevvie** [comment]
You will need to file an issue over at https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
