### ISSUE TITLE
Use GitHub Actions

### ISSUE THREAD

**Issue by KygekDev** [ItzLevvie/MicrosoftTeams-msinternal#4]
You can use **GitHub Actions** to automatically update and commit the `defconfig` and `defconfig2` files periodically instead of updating and committing it manually.

**Comment by ItzLevvie** [comment]
It's being worked on, but not a huge priority at the moment.

Node.js is somewhat a bit finicky for parsing JSON files, or doing multiple requests via a loop, so the code will need bunch of changes before automation can be done.

**Comment by edirimkus** [comment]
can you please explant how i can run it from github actions please

**Comment by nutterthanos** [comment]
only problem of github-actions is that the artifacts expire

**Comment by KygekDev** [comment]
> only problem of github-actions is that the artifacts expire

But we don't need to use artifacts in this repo...

**Comment by nutterthanos** [comment]
> > only problem of github-actions is that the artifacts expire
> 
> But we don't need to use artifacts in this repo...

oh right

**Comment by ItzLevvie** [comment]
It's now resolved in the latest commits as part of https://github.com/ItzLevvie/MicrosoftTeams-msinternal/pull/10.

I'll be monitoring it closely for any problems.
