### ISSUE TITLE
URLs for the latest production build of Microsoft Teams were updated yesterday, but the date there is 3 weeks ago

### ISSUE THREAD

**Issue by vlad8x8** [ItzLevvie/MicrosoftTeams-msinternal#42]
Hi
Thank you for this project.

I manually check https://github.com/ItzLevvie/MicrosoftTeams-msinternal/blob/master/defconfig if I need a link to the latest version.
Today I noticed, that URLs for the latest production build of Microsoft Teams were updated yesterday, but the date there is 3 weeks ago (October 12). https://github.com/ItzLevvie/MicrosoftTeams-msinternal/blame/master/defconfig
Does it mean that the date is wrong?

**Comment by ItzLevvie** [comment]
Those dates represents when the file was uploaded onto our CDN.

You will need to check https://learn.microsoft.com/en-us/officeupdates/teams-app-versioning for more accurate dates.
