### ISSUE TITLE
macOS: headphone microphone not working after waking macOS

### ISSUE THREAD

**Issue by Mateus109** [ItzLevvie/MicrosoftTeams-msinternal#43]
After waking macOS from screensaver or sleep, Teams is unable to pick up the headphone microphone (e.g. Plantronics C3220 USB-C).  **Only "New" Teams is affected**, all other apps and the OS pickup sound from the headphone microphone, but New Teams is silent.  Old Teams is unaffected by this bug.  Restarting Teams fixes the problem but it's very annoying.

**Comment by ItzLevvie** [comment]
You will need to file an issue over at https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472
