### ISSUE TITLE
Teams sharing broken with MacOS Sequoia

### ISSUE THREAD

**Issue by nickcheek** [ItzLevvie/MicrosoftTeams-msinternal#46]
Version 24152.405.2925.6762 (24152.405.2925.6762)

Teams share screen only shows grey boxes.  Teams classic worked but now new teams is forcing the switch.

**Comment by askpatrickw** [comment]
I can also reproduce this.

**Comment by nickcheek** [comment]
> I can also reproduce this.
> 
> This workaround works.
> 
> 
> 
> https://www.reddit.com/r/MacOSBeta/comments/1dg6e3c/macos_sequoia_teams_screen_sharing/

The workaround crashes teams for me a short time after enabling, the few times I've managed to make it work.

**Comment by askpatrickw** [comment]
Go upvote this.
https://feedbackportal.microsoft.com/feedback/idea/771aa679-d133-ef11-a296-000d3a044d12

**Comment by pallxk** [comment]
Screen sharing now works for me on Sequoia Beta 4 with the clean of teams data.

```sh
rm -rf ~/Library/Containers/com.microsoft.teams2*/
```

**Comment by askpatrickw** [comment]
It also works for me. I had to no cleaning. The last Sequoia build fixed it. Unclear if there was a Teams update in there since it auto updates.

**Comment by askpatrickw** [comment]
I think this can be closed.

**Comment by nickcheek** [comment]
> I think this can be closed.

Agreed, works for me also.
