### ISSUE TITLE
Just a question....difference between defconfig and defconfig2?

### ISSUE THREAD

**Issue by Lacipe** [ItzLevvie/MicrosoftTeams-msinternal#6]
I noticed that defconfig has newer electron builds and defconfig2 has a bit older electron builds but also new teams in it....why not just make 1 list?

**Comment by ItzLevvie** [comment]
> why not just make 1 list?

There are two reasons why it's done that way:
1) For `defconfig`: There are a lot of people using the `defconfig` file for web-automated scraping purposes; so merging both `defconfig` and `defconfig2` files into one file will break their automation workflow.

2) For `defconfig2`: Microsoft Internal only releases of the WebView2 version of Microsoft Teams are only useful for Microsoft employees and the adoption rates of the Electron releases compared to WebView2 is still very high.

That means if you are not a worker here at Microsoft, you will likely be automatically downgraded to the latest Public—or Public Preview if opted into one of the Windows Insider Program's channels—version.

This situation might change once work accounts are able to be added in the WebView2 version which is coming soon ;)
