### ISSUE TITLE
GCC/GCCH/DOD Builds?

### ISSUE THREAD

**Issue by miketheitguy** [ItzLevvie/MicrosoftTeams-msinternal#7]
https://github.com/ItzLevvie/MicrosoftTeams-msinternal/blob/22068b08dd32b474a17ae173fc6e7bada0f5138d/defconfig#L30

This link doesn't appear to have the downloads provided for GCCH. 

https://statics.teams.microsoft.com/production-osx/1.5.00.4683/Teams_osx.pkg
https://statics.teams.microsoft.com/production-windows-x64/1.4.00.32771/Teams_windows_x64.exe

Both URLs sourced from https://gov.teams.microsoft.us/download

I'm a GCCH user so not sure what the DOD/GCC build links are.

**Comment by ItzLevvie** [comment]
I have an experimental branch where this is being worked on: https://github.com/ItzLevvie/MicrosoftTeams-msinternal/blob/c707909fe080a9ee0a72a7a2ef0291e8f893d2f8/defconfig2#L131-L158

It'll be merged to the master branch once testing with CI/CD has finished.

**Comment by ItzLevvie** [comment]
It's now resolved in the latest commits as part of https://github.com/ItzLevvie/MicrosoftTeams-msinternal/pull/10.
