### ISSUE TITLE
MS Teams v1.5 on Linux ?

### ISSUE THREAD

**Issue by tianalemesle** [ItzLevvie/MicrosoftTeams-msinternal#8]
Hello,

Would it be possible to get MS Teams v1.**5** on Linux ?

Thanks !

**Comment by tianalemesle** [comment]
Unfortunately, this v1.5 doesn't have the same UI as the v1.5 for Windows & Mac, which is exactly what I'm looking for, in order to develop a side panel add-in. Thanks

**Comment by tianalemesle** [comment]
Hello ?

**Comment by ItzLevvie** [comment]
You'll need to send feedback through https://feedbackportal.microsoft.com as the Linux version is missing several features compared to the Windows / macOS versions.
